name: synthetic_bathymetry_inversion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  # add your dependencies here
  - polartoolkit==1.1.3
  - invert4geom=1.1.0
  - esmpy # needed for xesmf to install correctly
  - xesmf # needed for invert4geom noise contamination function
  - cmocean
  - adjusttext
  - shapely
  # dev
  - ipykernel
  - jupyterlab
  - pytest>=6
  - pytest-cov>=3
  # below packages need to be installed with pip (aren't available in conda-forge)
  # - pip
  # - pip:
  #     -
