name: synthetic_bathymetry_inversion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  # add your dependencies here
  # - polartoolkit>=0.9 # install locally
  # - invert4geom>=0.13 # install locally
  - geopandas
  - pygmt
  - pyogrio
  - esmpy
  - xesmf
  - cmocean
  - jupyterlab_execute_time
  - adjusttext
  - boule
  - shapely
  # for dev purposes
  - ipykernel
  - pre-commit
  - pylint
  - pytest
  - pip
  # only if can't install with conda
  - pip:
      - kneebow
