name: synthetic_bathymetry_inversion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  # add your dependencies here
  - polartoolkit>=1
  - invert4geom>=1
  - geopandas
  - pygmt
  - pyogrio
  - esmpy # needed for xesmf to install correctly
  - xesmf # need for invert4geom noise contamination function
  - cmocean
  - adjusttext
  - shapely
  # for dev purposes
  - ipykernel
  - pre-commit
  - pylint
  - pytest
  # - pip
  # only if can't install with conda
  # - pip:

